### PR TITLE
New theme system and new themes

### PR DESCRIPTION
**Pull request by adeneys**
Added a new theme system
Added 3 new responsive themes
Update markup to use HTML 5

### CODE REVIEW

**Comment by alan-null** [comment]
@adeneys 

### Issues:
**Missing bower**
- missing dependencies in `package.json`
- missing instructions in `how to build.md`
```
npm install bower -g
bower install
```
some themes require for example **jsurl**

**Obsolete code**
Do you want to clean this later? I would prefer to clean this up before release. We need a task if this won't be solved in this branch.
```html
        <!-- start: deprecated. The following view is deprecated and will be removed in a future release. -->
        @Html.Sitecore().Rendering("{7BDD6111-5B6C-4904-8FA2-E6A334FE675E}", new { Cacheable = true, CacheKey = "ThemeIncludes", Cache_VaryByData = true })
        <!-- end: deprecated -->
```

**jQuery conflict**
I am getting this while using our themes with our jQuery.
image

Console log:
```javascript
Uncaught TypeError: element.attachEvent is not a function   prototype.js:5653 
```


### Suggestions
**Visual Studio**
What do you think about visual studio integration? It is already there, we could only move folders and files to enable it. 
image

**Comment by ddysart** [comment]
I am pretty sure that jQuery issue is a known issue with Sitecore, though I thought v8.1 Update 2 fixed it. I do know there is a hottix for it that I'll dig up.

**Comment by adeneys** [comment]
The jQuery issue is probably because I'm not using noconflict. I'll add that in when I make the above changes.

**Comment by adeneys** [comment]
- I updated the build instructions to include the missing Bower stuff.
- We should leave the old theme view (and control) for now. This is the first release with the new themes and we need to allow people to transition over before removing those views/controls. Although, the markup has changed so existing themes will need updating.
- I added jQuery.noConflict to all themes to avoid issues in PE/EE
- We can look at VS task runner integration later. The current tasks require parameters to be passed which will complicate the integration. We can look at that later on while restructuring the project.

**Comment by alan-null** [comment]
Great. Everything works fine now.

Let's just fix that css issue and we are ready to merge.
css selector issue
```css
* {
  box-sizing: border-box;
}
```

**Comment by adeneys** [comment]
Done!

**Comment by alan-null** [comment]
I don't feel that we are working in different time zones ;)

**Comment by adeneys** [comment]
Not for much longer :)

**Pull request merged**
